site_name: py3html
site_url: https://ozcanyarimdunya.github.io/py3html/
site_author: Özcan Yarımdünya
site_description: Python to HTML
repo_url: https://github.com/ozcanyarimdunya/py3html

plugins:
  - search
theme:
  name: readthedocs
