name: 'run-checks'
description: 'Composite action to run linter for code formatting and to run the unittests.'
runs:
  using: 'composite'
  steps:
    - name: Run linter
      run: make lint
      shell: bash
    - name: Test with pytest
      run: make test
      shell: bash
