name: commander-build

on:
  push:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env
      - name: Lint and test
        uses: ./.github/workflows/lint-and-test

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env
      - name: Publish to pypi
        run: make publish-pypi
        shell: bash
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  documentation:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry-env
      - name: Publish site to the GitHub pages
        run: make gh-deploy
        shell: bash
